const students = [
  {
    names: 'Alec Parisian',
    roll: 20,
    age: 48,
    classe: 3,
    gender: 'Male',
    location: 'virginia',
    fees: 302,
  },
  {
    names: 'Dillon Jerde',
    roll: 53,
    age: 34,
    classe: 4,
    gender: 'Female',
    location: 'Montana',
    fees: 130,
  },
  {
    names: 'Foster Harvey',
    roll: 11,
    age: 23,
    classe: 3,
    gender: 'Male',
    location: 'Montana',
    fees: 520,
  },
  {
    names: 'Ima Smitham',
    roll: 42,
    age: 15,
    classe: 4,
    gender: 'Female',
    location: 'Virginia',
    fees: 900,
  },
  {
    names: 'Arwec Pawisi',
    roll: 24,
    age: 19,
    classe: 5,
    gender: 'Female',
    location: 'Texas',
    fees: 892,
  },
  {
    names: 'Disla Jerdem',
    roll: 53,
    age: 34,
    classe: 4,
    gender: 'Female',
    location: 'Montana',
    fees: 240,
  },
  {
    names: 'Iua Smetham',
    roll: 32,
    age: 12,
    classe: 3,
    gender: 'Female',
    location: 'Virginia',
    fees: 350,
  },
  {
    names: 'Trisha Kerluke',
    roll: 43,
    age: 18,
    classe: 3,
    gender: 'Male',
    location: 'Virginia',
    fees: 640,
  },
  {
    names: 'Iva Smithbm',
    roll: 12,
    age: 19,
    classe: 3,
    gender: 'Female',
    location: 'Montana',
    fees: 742,
  },
  {
    names: 'Zvan Mithim',
    roll: 124,
    age: 26,
    classe: 3,
    gender: 'Female',
    location: 'Montana',
    fees: 822,
  },
];
